str = ''
str +='<ul class="left_menu">'
str +='   <li>'
str +='      <a href="2020-0-componant.html"><span>Componant</span></a>'
str +='      <ul>'
str +='         <li><a href="component.html">component</a></li>'
str +='         <li><a href="2020-0-componant.html">2020-0-compornent</a></li>'
str +='         <li><a href="2020-1-componant.html">2020-1-compornent</a></li>'
str +='         <li><a href="color.html">color</a></li>'
str +='         <li><a href="css_tip.html">css_tip</a></li>'
str +='      </ul>'
str +='   </li>'
str +='   <li>'
str +='      <a href="fonts.html"><span>Font</span></a>'
str +='      <ul>'
str +='         <li><a href="fonts.html"><span>Font</span></a></li>'
str +='         <li><a href="logo.html"><span>Logo</span></a></li>'
str +='      </ul>'
str +='   <li>'
str +='      <a href="fullpage.html"><span>jquery</span></a>'
str +='      <ul>'
str +='         <li><a href="fullpage.html">fullpage</a></li>'
str +='         <li><a href="accordion.html">accordion</a></li>'
str +='         <li><a href="jquery_tip.html">jquery_tip</a></li>'
str +='         <li><a href="masonry.html">masonry</a></li>'
str +='      </ul>'
str +='    </li>'
str +='   <li>'
str +='      <a href="slick-slider.html"><span>slider</span></a>'
str +='      <ul>'
str +='         <li><a href="slick-slider.html">slick-slider</a></li>'
str +='         <li><a href="swiper.html">swipper-slider</a></li>'
str +='      </ul>'
str +='   </li>'
str +='</ul>'

document.write( str );